version: '3'

services:
  node-app:
    container_name: node-container
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo-container
    image: mongo
    ports:
      - "27017:27017"
    
  